theme: jekyll-theme-minimal
title: Pervasive Software Lab (PSLab)
logo: https://pslabunibo.github.io/images/pslab_logo.png
show_downloads: false
description: A research laboratory of the Computer Science and Engineering Department at the University of Bologna, Italy<br><br><h1>Peoples</h1><br><h3>Director</h3><br><ul><li>Prof. Mirko Viroli</li></ul><h3>Full Members</h3><ul><li>Prof. Antonio Natali</li><li>Prof. Andrea Omicini</li></ul>
