# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "PSLAB"
title_separator: "|"
masthead_title: "Pervasive Software Lab"
subtitle: "Research Lab"
name: "Pervasive Software Lab @ Alma Mater Studiorum - Università di Bologna"
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Pervasive software lab @ unibo
logo: /assets/images/pslab_logo.png

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

github_username:  pslabunibo

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.21.0"
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

plugins:
  - jekyll-feed
  - jekyll-include-cache
  
include: ["_pages"]

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
