theme: jekyll-theme-minimal
title: Pervasive Software Lab (PSLab)
description: A research laboratory of the Computer Science and Engineering Department at the University of Bologna, Italy
logo: images/pslab_logo.png
show_downloads: false
